### ISSUE TITLE
Pictures for welcome slides

### ISSUE THREAD

**Issue by markdunning** [datachampcam/friendly-github-intro#1]
If you want a picture of yourself to appear on the welcome slides please email one to myself or Anne.

Cheers,

Mark

**Comment by hornsinthelibrary** [comment]
I've sent you one just now Mark. Thanks!

**Comment by markdunning** [comment]
Thanks! I have added to the slides

**Comment by teatree1212** [comment]
sent

**Comment by markdunning** [comment]
Thanks both.
